Home
dafegosa/CondoAppmin pull request #10
Opened 2020-11-21 22:27 UTC by alejo9226

### Add home, login and register routes

Add home, login and register routes and their components completely styled. Also added requests to register component to create admins into the database

<img width="1440" alt="Screen Shot 2020-11-21 at 17 22 22" src="https://user-images.githubusercontent.com/20896104/99888882-20734b80-2c1e-11eb-8943-4673bcf5aba6.png">
<img width="1440" alt="Screen Shot 2020-11-21 at 17 22 38" src="https://user-images.githubusercontent.com/20896104/99888887-29641d00-2c1e-11eb-9508-c9decc82c7a6.png">
<img width="1440" alt="Screen Shot 2020-11-21 at 17 22 52" src="https://user-images.githubusercontent.com/20896104/99888893-33861b80-2c1e-11eb-85e1-fa6458304e85.png">
<img width="1440" alt="Screen Shot 2020-11-21 at 17 24 54" src="https://user-images.githubusercontent.com/20896104/99888917-7cd66b00-2c1e-11eb-8458-0748d8d26900.png">
<img width="1175" alt="Screen Shot 2020-11-21 at 17 26 25" src="https://user-images.githubusercontent.com/20896104/99888947-b1e2bd80-2c1e-11eb-8fc6-47cbda979a8a.png">

2020-11-22 02:39 UTC, dafegosa commented on src/App.js
> +    // this.setState({ [e.target.name]: e.target.value })
Quitar los comentarios

2020-11-22 02:40 UTC, dafegosa commented on src/App.js
> +    // console.log(this.state)
Quitar los comentarios

2020-11-22 02:41 UTC, dafegosa commented on src/App.js
> +    /* this.setState({
Igual, todo esto está comentado?

2020-11-22 02:43 UTC, dafegosa commented on src/pages/register/Register.js
> +    console.log(e.target)
Quitar los console.log

2020-11-22 02:43 UTC, dafegosa commented on src/pages/register/Register.js
> +    console.log(newUser)
Quitar console.log

2020-11-22 02:44 UTC, dafegosa commented on src/pages/register/Register.js
> +      console.log(data.message);
console.log

2020-11-22 02:45 UTC, dafegosa requested changes

2020-11-22 02:45 UTC, dafegosa commented on src/pages/register/Register.js
> +      console.log(err)
console.log

2020-11-22 23:03 UTC, dafegosa approved these changes

2020-11-23 13:18 UTC, simonhoyos approved these changes

2020-11-23 13:43 UTC, merged