Private dashboard
dafegosa/CondoAppmin pull request #13
Opened 2020-11-24 17:47 UTC by alejo9226

### Add PrivateRouter for dashboard

Wrapped dashboard route in a PrivateRouter for authentication.

<img width="1438" alt="Screen Shot 2020-11-24 at 12 46 01" src="https://user-images.githubusercontent.com/20896104/100132158-040c2480-2e53-11eb-8821-06f17809ef8b.png">
<img width="1440" alt="Screen Shot 2020-11-24 at 12 46 26" src="https://user-images.githubusercontent.com/20896104/100132201-12f2d700-2e53-11eb-86b7-8875878130a3.png">

2020-11-24 21:22 UTC, simonhoyos requested changes

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/components/UserSection.js
> +const UserOptionsList = styled.ul``
Si no se está aplicando ningún estilo es mejor no crear un styled component

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/Dashboard.js
> +        statePart.name = condoName
En general es mejor evitar los side effects. Cuando modificamos los argumentos de una función estámos causando un side effect. Es mejor crear un nuevo objeto que tenga todas las propiedades de statePart más las propiedades que queremos agregar o modificar

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/Dashboard.js
> +      /* this.setState({...this.state, name: '', address: '', message: data.message}) */
No dejar comentarios en el código

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/Dashboard.js
> +    /* const { adminName, adminid, condoName, condoAddress, condoid } = this.state */
No dejar comentarios

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/Dashboard.js
> +          history={history}
Está bien pasar el history por props pero recuerda que también tenemos a nuestra disposición el HOC withRouter y el hook useHistory para tener acceso a estas propiedades desde cualquier componente

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/components/UserSection.js
> +    let { renderOptions } = this.state
Este valor no se debería modificar. Por seguridad puedes usar const

2020-11-24 21:22 UTC, simonhoyos commented on src/pages/dashboard/components/content/Content.js
> +        return <ContentAddCondos
Puedes agregar paréntesis después del return para que la identación se vea más organizada

2020-11-24 23:46 UTC, alejo9226 commented on src/pages/dashboard/components/UserSection.js
> +const UserOptionsList = styled.ul``
eliminado

2020-11-24 23:46 UTC, alejo9226 commented on src/pages/dashboard/Dashboard.js
> +          history={history}
Agregué el withRouter donde necesito usarlo

2020-11-25 15:11 UTC, simonhoyos approved these changes

2020-11-25 15:42 UTC, dafegosa approved these changes

2020-11-25 15:44 UTC, merged