Register and login
dafegosa/CondoAppmin pull request #15
Opened 2020-11-25 19:16 UTC by dafegosa

Resolve merge conflicts with development branch

2020-11-25 21:59 UTC, simonhoyos requested changes

2020-11-25 21:59 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +  getUsers = () => {
puedes cambiarle el nombre a este método. Si la idea es obtener los tickets el nombre puede ser `getTickets`

2020-11-25 21:59 UTC, simonhoyos commented on src/pages/dashboard/components/TopBar.js
> +    const { history } = this.props;
history no se esta usando, se puede borrar

2020-11-25 22:01 UTC, simonhoyos commented
La finalidad de este PR no es clara. Agrega más detalles de lo que se quiere lograr en este PR en su descripción. 

Adicionalmente hay demasiados archivos modificados que no tienen ninguna relación, es recomendado mantener los PR más especificos a la tarea que se está resolviendo

2020-11-26 03:22 UTC, dafegosa commented
Si @simonhoyos, la verdad para la presentación de proyectos de ayer, unimos ramas que teníamos por separado y que faltaban por hacerles pull request. En este Pr encuentras entonces archivos que estaban en una rama de Alejo Alfaro, pero ya tiene las actualizaciones que fueron aceptadas. Evitaremos hacer esto para la próxima.

2020-11-26 13:32 UTC, simonhoyos approved these changes

2020-11-26 15:09 UTC, alejo9226 approved these changes

2020-11-26 15:43 UTC, merged