With docker
dafegosa/CondoAppmin pull request #25
Opened 2020-12-09 05:25 UTC by dafegosa

Add Dockerfile
Add CKfinder

Incorporate images into ticket body

![image](https://user-images.githubusercontent.com/17477347/101588697-f8713f80-39b4-11eb-9ebc-622c55e75b20.png)

2020-12-09 11:03 UTC, simonhoyos commented
Este PR está apuntando a master

2020-12-09 15:35 UTC, dafegosa commented
@simonhoyos  Ohhh, de nuevo.... Listo, Ya está apuntando a development

2020-12-09 18:43 UTC, simonhoyos requested changes

2020-12-09 18:43 UTC, simonhoyos commented on dsadq
> +                   SSUUMMMMAARRYY OOFF LLEESSSS CCOOMMMMAANNDDSS
Este archivo no hace parte del código

2020-12-10 13:26 UTC, simonhoyos approved these changes

2020-12-10 16:08 UTC, alejo9226 approved these changes

2020-12-10 16:08 UTC, merged