Fix unit route
dafegosa/CondoAppmin pull request #28
Opened 2020-12-15 17:16 UTC by alejo9226

### Fix unit route

Add top-left dropdown to choose current working condo. Added add and list tabs for units, which inside allows for unit edition and deletion

<img width="1440" alt="Screen Shot 2020-12-15 at 12 14 11" src="https://user-images.githubusercontent.com/20896104/102248308-0cde9c00-3ecf-11eb-9b12-e70ef2e61d17.png">
<img width="1440" alt="Screen Shot 2020-12-15 at 12 14 24" src="https://user-images.githubusercontent.com/20896104/102248338-149e4080-3ecf-11eb-9977-18739ab603db.png">
<img width="1440" alt="Screen Shot 2020-12-15 at 12 14 50" src="https://user-images.githubusercontent.com/20896104/102248409-241d8980-3ecf-11eb-9a2e-72d6dd546b5b.png">
<img width="1440" alt="Screen Shot 2020-12-15 at 12 15 07" src="https://user-images.githubusercontent.com/20896104/102248439-2da6f180-3ecf-11eb-8334-579c0d099a90.png">

2020-12-15 19:03 UTC, simonhoyos requested changes

2020-12-15 19:03 UTC, simonhoyos commented on src/pages/dashboard/components/content/units/ContentGetUnits.js
> +const UnitNameInput = styled.input`
Si no tiene estilos no es necesario crear un styled component

2020-12-16 14:41 UTC, simonhoyos approved these changes

2020-12-29 00:57 UTC, dafegosa approved these changes

2020-12-29 02:39 UTC, merged