New tickets content
dafegosa/CondoAppmin pull request #29
Opened 2020-12-17 03:55 UTC by dafegosa

Muestra el historial de tickets. Enviados si es residentes, recibidos si es admin. 
Admin, no tiene acceso a botón de crear tickets
![image](https://user-images.githubusercontent.com/17477347/102441858-20822380-3ff1-11eb-880a-639845f5c214.png)

Limita a un residente a tener un ticket abierto a la vez, hasta no ser solucionado no se pueden crear más.
![image](https://user-images.githubusercontent.com/17477347/102441891-2d067c00-3ff1-11eb-814f-9f6cf2aa2830.png)
 

En el historial de Tickets, al abrir el ticket, si este está en estado activo permite agregar nuevos comentarios por parte del residente y del administrador.
![image](https://user-images.githubusercontent.com/17477347/102441941-44de0000-3ff1-11eb-8115-6aeb40bf4aaa.png)

El administrador tiene capacidad de cerrar el ticket
![image](https://user-images.githubusercontent.com/17477347/102441956-4efffe80-3ff1-11eb-9777-6158205c21ce.png)

 

Los comentarios, o respuestas a un ticket, se denominan subTickets dentro del código. Estos son renderizados debajo del ticket al que pertenecen a medida que se van enviando por parte del administrador (libertador@gmail.com) o del residente (lapola@gmail.com) 
![image](https://user-images.githubusercontent.com/17477347/102442015-6808af80-3ff1-11eb-8314-b72179c90c7c.png)

Al solucionar el ticket, se tiene acceso al historial de conversación pero ya no se puede comentar sobre el mismo:
![image](https://user-images.githubusercontent.com/17477347/102442041-748d0800-3ff1-11eb-93cd-923300c1bf9a.png)

 

En el menú de mano derecha aparece la notificación para el administrador al momento de recibir un nuevo ticket, y para el administrador y el residente al recibir una contestación de la otra parte
![image](https://user-images.githubusercontent.com/17477347/102442096-8ec6e600-3ff1-11eb-9e3e-818391d08635.png)

 

Los tickets se organizan en el historial, mostrando al inicio de la lista el último recibido. Se diferencian los tickets en estado activo (Negrilla)  de los tickets de estado solucionado.
![image](https://user-images.githubusercontent.com/17477347/102442114-9a1a1180-3ff1-11eb-83c0-c0cb14d9e585.png)

 

La mayor parte de las actualizaciones están hechas en el contenedor ShowMessage.
Al crear un subticket (Responder), Se envía la información a una nueva tabla denominada subtickes

2020-12-17 13:25 UTC, simonhoyos requested changes

2020-12-17 13:25 UTC, simonhoyos commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
El archivo .env debería estar ignorado. Luego de agregarlo al .gitignore puedes correr el comando `git rm --cached .env` para removerlo por complete del git

2020-12-17 13:25 UTC, simonhoyos commented on src/pages/dashboard/components/content/AllMessages/CentralMessagesList.js
> +  // useEffect(() => {
Borrar el código comentado

2020-12-17 13:25 UTC, simonhoyos commented on src/pages/dashboard/components/content/add-residents/ContentAddResident.js
> +          {/* {!!units &&
Borrar el código comentado

2020-12-17 13:25 UTC, simonhoyos commented on src/store/messageReducer.js
> +      console.dir(err)
ojo con los console logs

2020-12-18 04:57 UTC, dafegosa commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
done!

2020-12-18 11:21 UTC, simonhoyos requested changes

2020-12-18 11:21 UTC, simonhoyos commented on src/pages/dashboard/components/content/AllMessages/CentralMessagesList.js
> +    const thisId = id
Alguna razón para crear esta variable y no pasar el id directamente?

2020-12-18 15:32 UTC, dafegosa commented on src/pages/dashboard/components/content/AllMessages/CentralMessagesList.js
> +    const thisId = id
No ninguna, en ese momento por alguna razón, no me funcionó pasando directamente el id. Pero Acabo de probar y todo en orden. Modifiqué esa linea.

2020-12-18 18:34 UTC, simonhoyos commented on src/store/messageReducer.js
> +      console.dir(err)
Todavía está el console dir

2020-12-29 02:54 UTC, alejo9226 approved these changes

2020-12-30 00:27 UTC, simonhoyos approved these changes

2021-01-19 04:31 UTC, closed without merging