Messages
dafegosa/CondoAppmin pull request #5
Opened 2020-11-13 05:40 UTC by dafegosa

Create messages area and it use mock data (data folder) to show the ticket and messages.
Messages Area is called from dashboard.js

![image](https://user-images.githubusercontent.com/17477347/99033420-d537a980-2548-11eb-9681-1544b42df243.png)

![image](https://user-images.githubusercontent.com/17477347/99033431-d9fc5d80-2548-11eb-8998-59155e52ce05.png)

2020-11-13 16:24 UTC, simonhoyos requested changes

2020-11-13 16:24 UTC, simonhoyos commented on src/pages/MessagesArea.js
>          <Message2>
Por qué rendirzar los mensajes uno por uno y no con un map? Es por los estilos?

Para no tener que crear 4 componentes diferente podrías aprovecharte del pseudo-selector de css `:nth-child`

```javascript
const Message = styled.div`
  // css en común

  &:nth-child(1) {
    // estilos del primer mensaje
  }

  &:nth-child(2) {
    // estilos del segundo mensaje
 }
`
```

O quizás `grid` no sea la mejor opción para usar en este caso y puede que `flexbox` sea una mejor opción

2020-11-14 16:18 UTC, alejo9226 requested changes

2020-11-14 16:18 UTC, alejo9226 commented on src/pages/dashboard/Dashboard.js
> +import MessagesArea from "../MessagesArea";
Este componente puede ir dentro de la carpeta components que esta en pages/dashboard/components ya que es un hijo del dashboard

2020-11-14 16:18 UTC, alejo9226 commented on src/pages/MessagesArea.js
> +import { messages_data } from "../data/messages_data.js";
La data podria ir dentro de una carpeta en pages/dashboard/ ya que es algo que se muestra unicamente en la ruta /dashboard

2020-11-14 16:18 UTC, alejo9226 commented on src/pages/MessagesArea.js
> +const ContenedorMensajes = styled.div`
Los componentes deben tener nombres en ingles

2020-11-14 17:12 UTC, simonhoyos requested changes

2020-11-14 17:12 UTC, simonhoyos commented on src/pages/MessagesArea.js
> +  /* grid-column: 2 / 2;
Los comentarios en general se consideran código muerto. Es mejor borrarlos si no se van a usar

2020-11-14 17:12 UTC, simonhoyos commented on src/pages/MessagesArea.js
> +  height: 90vh;
Por ahora podemos dejar la altura de esta forma. Cuando configuramos la altura en vh esto puede traer problemas cuando el usuario por ejemplo cambia el tamaño de la pantalla y el componente reduce su tamaño.

2020-11-14 17:12 UTC, simonhoyos commented on src/pages/MessagesArea.js
> +          <Message1>
Ahora que solo hay un componente de Message podriamos quitarle el 1 del nombre

2020-11-15 07:05 UTC, dafegosa commented on src/pages/MessagesArea.js
> +import { messages_data } from "../data/messages_data.js";
Pienso que la data es algo más global: En el registro, por ejemplo, debemos acceder a ella, y no hace parte de dashboard. Igual esto es temporal.

2020-11-15 07:05 UTC, dafegosa commented on src/pages/dashboard/Dashboard.js
> +import MessagesArea from "../MessagesArea";
done!

2020-11-15 07:09 UTC, dafegosa commented on src/pages/MessagesArea.js
> +  height: 90vh;
![image](https://user-images.githubusercontent.com/17477347/99179033-9429cb80-26e7-11eb-9401-4a415a820ce3.png)

Modificada la unidad de medida vh por %.

2020-11-15 07:10 UTC, dafegosa commented on src/pages/MessagesArea.js
> +          <Message1>
![image](https://user-images.githubusercontent.com/17477347/99179051-c3403d00-26e7-11eb-8483-b638d77de6f5.png)

¡hecho!

2020-11-15 07:12 UTC, dafegosa commented on src/pages/MessagesArea.js
> +const ContenedorMensajes = styled.div`
![image](https://user-images.githubusercontent.com/17477347/99179068-eff45480-26e7-11eb-98dc-f85e3ec15007.png)

2020-11-15 07:25 UTC, dafegosa commented
Antes de hacer los cambios, hice merge con la rama que creó Alejandro Alfaro que está pendiente por revisar (Dashboard top user).

2020-11-15 19:50 UTC, simonhoyos requested changes

2020-11-15 19:50 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +        {messages_data.map((messages) => (
Recuerda que es buena idea hacer la validación que de los mensajes exitan, y que sean un arreglo.

Aunque nombrar las variables con snake_case funciona la convención en javascript es siempre utilizar camelCase

2020-11-15 19:50 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +          <Message>
Recuerda agregarle el prop key al renderizar listas dinámicamente

2020-11-15 19:50 UTC, simonhoyos commented on src/pages/dashboard/components/UserSection.js
> +    }, () => console.log('current', this.state))
Borrar console.log

2020-11-15 20:53 UTC, dafegosa commented on src/pages/dashboard/components/MessagesArea.js
> +        {messages_data.map((messages) => (
Ok , muchas gracias por tus apreciaciones. Ajustes hechos.

2020-11-16 15:15 UTC, simonhoyos requested changes

2020-11-16 15:15 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +        {ticketsData.map(
Es buena idea agregar acá una validación para saber que `ticketsData` si existe y que sea un arreglo antes de hacer el `map`

2020-11-16 15:15 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +              <Message key={ticketsData.id}>
Qué es ticketsData? Tu quieres obtener el `id` de los tickets o de cada uno de los tickets. Si miras las herramientas del desarrollador en el navegador te debe estas saliendo una alerta que dice que debes agregarle la propiedad key a cada elemento de la lista, eso porque en este caso le estas asignando `undefined` a la propiedad key

2020-11-16 15:15 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +        {messagesData.map((messages) => (
lo mismos que ambos comentarios de la iteración anterior

2020-11-17 15:25 UTC, simonhoyos requested changes

2020-11-17 15:25 UTC, simonhoyos commented on public/index.html
> -  <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
No borraría ninguna de las lineas que se borraron de este archivo. Mejor si necesito cambiarlos, modificaría los iconos.

Estos iconos son los que se muestran en el tab del navegador, en dispositivos móviles y otros

2020-11-17 15:25 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +              ticketsData && (
esta validación de ticketsData sobra. Ya se hizo antes de mapear los datos

2020-11-17 15:52 UTC, dafegosa commented on src/pages/dashboard/components/MessagesArea.js
> +              ticketsData && (
Simón, ¿entonces solo dejar la validación de línea 66, y las validaciones que se hacen dentro del .map quitarlas?

2020-11-17 16:09 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +              ticketsData && (
Si esa que está dentro del map la puedes quitar (ln 77). Las demás si las dejas

2020-11-17 23:06 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +              ticketsData && (
@dafegosa solo faltaría este cambio por resolver y queda aprovado

2020-11-17 23:30 UTC, dafegosa commented on src/pages/dashboard/components/MessagesArea.js
> +              <p key={messages.id}>{messages.body}</p>
Simón, en la última actualización quito la validación interna. ¿así no estaría bien?

2020-11-17 23:31 UTC, dafegosa commented on src/pages/dashboard/components/MessagesArea.js
> +              <p key={messages.id}>{messages.body}</p>
@simonhoyos

2020-11-18 02:01 UTC, alejo9226 commented on src/App.js
> +  mainColor: "rgba(96, 125, 139, 1)",
Dani habiamos acordado dejar comillas simples

2020-11-18 02:07 UTC, alejo9226 requested changes
Solo ponernos de acuerdo con comillas simples

2020-11-18 11:46 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +              <p key={messages.id}>{messages.body}</p>
@dafegosa fíjate que si hayas subido los cambios. Yo aún sigo viendo la validación interna

2020-11-18 16:59 UTC, dafegosa commented on src/pages/dashboard/components/MessagesArea.js
> +              <p key={messages.id}>{messages.body}</p>
ok @simonhoyos , ¿podrías revisarlo nuevamente por favor? creo que ya está.

![image](https://user-images.githubusercontent.com/17477347/99561965-8bf6b800-2995-11eb-9743-f0976e989a1e.png)

![image](https://user-images.githubusercontent.com/17477347/99561941-8600d700-2995-11eb-9ba6-5f49bce02f14.png)

2020-11-18 18:21 UTC, simonhoyos approved these changes

2020-11-19 03:04 UTC, dafegosa commented on src/App.js
> +  mainColor: "rgba(96, 125, 139, 1)",
Listo, hecho con comillas sencillas.

2020-11-19 03:05 UTC, alejo9226 approved these changes

2020-11-19 03:16 UTC, merged