Dashboard top user
dafegosa/CondoAppmin pull request #6
Opened 2020-11-14 21:22 UTC by alejo9226

## Add dashboard top user section 

This task adds the dashboard top user section styles and responsiveness for <500px screens, <768px screens and >768px screens

**After**

<img width="1432" alt="Screen Shot 2020-11-14 at 16 18 15" src="https://user-images.githubusercontent.com/20896104/99157214-058c5e80-2695-11eb-96b7-57770e8c79a0.png">
<img width="777" alt="Screen Shot 2020-11-14 at 16 18 55" src="https://user-images.githubusercontent.com/20896104/99157229-1b018880-2695-11eb-920e-052817f5dc21.png">
<img width="485" alt="Screen Shot 2020-11-14 at 16 19 16" src="https://user-images.githubusercontent.com/20896104/99157240-281e7780-2695-11eb-8b9c-4ebe57ff3a98.png">

2020-11-15 19:34 UTC, simonhoyos requested changes

2020-11-15 19:34 UTC, simonhoyos commented on src/pages/dashboard/components/UserSection.js
> +    }, () => console.log('current', this.state))
Puedes borrar los console.logs, es mejor no dejarlos en el código final

2020-11-16 01:48 UTC, dafegosa approved these changes

2020-11-16 15:52 UTC, alejo9226 commented on src/pages/dashboard/components/UserSection.js
> +    }, () => console.log('current', this.state))
Done

2020-11-16 18:58 UTC, simonhoyos approved these changes

2020-11-17 00:30 UTC, merged