Dashboard left
dafegosa/CondoAppmin pull request #7
Opened 2020-11-17 00:27 UTC by Prometheus1985

## Add dashboard-left menu

Left side menu was added with icons and anchor tags, each **LINK** element will be linked to a route inside the app.
A mock logo was added

![image](https://user-images.githubusercontent.com/60072047/99323959-3610fb80-2841-11eb-8353-98520ebf2f4a.png)

2020-11-17 15:13 UTC, simonhoyos requested changes

2020-11-17 15:13 UTC, simonhoyos commented on src/pages/MessagesArea.js
> +          <h3>{tickets_data[0].title}</h3>
Estos cambios ya los había comentado en un PR anterior y ya se había cambiado la implementación. Creaste la rama para este PR desde develop?

2020-11-17 15:13 UTC, simonhoyos commented on src/pages/dashboard/components/LeftMenu.js
> +              <span>Mensajes</span>
Podríamos manejar la lista de links desde un arreglo. Si en el futuro queremos agregar un nuevo link simplemente sería agregar un nuevo elemento a ese arreglo y de ese forma no tenemos que modificar el HTML

2020-11-18 00:14 UTC, Prometheus1985 commented on src/pages/dashboard/components/LeftMenu.js
> +              <span>Mensajes</span>
Se cambió la estructura del menú izquierdo, ahora cada item es cargado desde un map:
`
const leftMenuNav = [
    {
      name: 'Mensajes',
      icon: 'fas fa-envelope',
    },
    { name: 'Pagos', icon: 'fas fa-money-check-alt' },
    { name: 'Eventos', icon: 'fas fa-calendar-alt' },
    { name: 'Tickets', icon: 'fas fa-comment-dots' },
    { name: 'Crear perfil', icon: 'fas fa-user-plus' },
  ]
`

`
<SideMenu>
        <ul>
          {leftMenuNav.map((el) => (
            <Select>
              <i class={el.icon}></i>
              <li>{el.name}</li>
              <br />
            </Select>
          ))}
        </ul>
      </SideMenu>
`

2020-11-18 01:50 UTC, alejo9226 commented on src/data/units_data.js
> +export const units_data = [
La variable podria ser nombrada en camelCase, como unitsData

2020-11-18 01:55 UTC, alejo9226 approved these changes

2020-11-18 11:43 UTC, simonhoyos commented on src/pages/dashboard/components/LeftMenu.js
> +              <span>Mensajes</span>
Estos cambios están en otra rama?

2020-11-18 22:10 UTC, Prometheus1985 commented on src/pages/dashboard/components/LeftMenu.js
> +              <span>Mensajes</span>
No, están en dashboard-left, la misma rama del primer pull.

2020-11-19 13:22 UTC, simonhoyos commented
@Prometheus1985 puedes resolver los conflictos y luego le doy otra miradita para aprovarlo

2020-11-19 22:22 UTC, Prometheus1985 commented
Hola @simonhoyos, ya resolví los conflictos. Quedo atento.

2020-11-19 22:51 UTC, simonhoyos approved these changes

2020-11-21 14:26 UTC, alejo9226 approved these changes

2020-11-21 14:31 UTC, merged