Register and login
dafegosa/CondoAppmin pull request #9
Opened 2020-11-17 18:28 UTC by dafegosa

Add Register and Login Components
![image](https://user-images.githubusercontent.com/17477347/99431283-812a1d80-28d8-11eb-98ab-7f44c8947426.png)

![image](https://user-images.githubusercontent.com/17477347/99431379-ad459e80-28d8-11eb-95ba-642b0810be7c.png)

The register data is stored in an array called usersData

2020-11-17 23:13 UTC, simonhoyos reviewed
Las ramas si se las estás creando a partir de develop? estás actualizando develop siempre antes de crear una nueva rama?

Veo muchos cambios que vienen duplicados desde otras ramas, esto lo que hace es contaminar el PR, hace más difícil su lectura y facilita la introducción de bugs y nuevos errorres

2020-11-17 23:13 UTC, simonhoyos commented on src/pages/Login.js
> +    console.log(result);
borrar console.logs

2020-11-17 23:13 UTC, simonhoyos commented on src/pages/Login.js
> +    console.log(validUser);
borrar console.logs

2020-11-17 23:13 UTC, simonhoyos commented on src/pages/Login.js
> +    console.log("ok");
borrar console.logs

2020-11-17 23:13 UTC, simonhoyos commented on src/pages/Register.js
> +      () => console.log("current", this.state)
borrar console.logs

2020-11-17 23:13 UTC, simonhoyos commented on src/pages/Register.js
> +    console.log(this.state.users);
Lo mismo

2020-11-17 23:13 UTC, simonhoyos commented on src/pages/dashboard/components/MessagesArea.js
> +              ticketsData && (
Cambios duplicados desde otra rama.

2020-11-17 23:13 UTC, simonhoyos commented on src/data/ticketsData.js
> +export const ticketsData = [
Cambios duplicados

2020-11-17 23:13 UTC, simonhoyos commented on src/data/messagesData.js
> +export const messagesData = [
Cambios duplicados

2020-11-17 23:40 UTC, dafegosa commented
Si, error mío, Realmente hago el pull de todo y le hice merge a la nueva rama con la información de ramas que aún no han sido aprobadas. ¡Lo siento! Aprendida la lección.

2020-11-19 02:58 UTC, alejo9226 approved these changes

2020-11-19 15:35 UTC, simonhoyos requested changes

2020-11-19 15:35 UTC, simonhoyos commented on .vscode/settings.json
> +<<<<<<< HEAD
ojo, acá habían conflictos, hay que arreglar este archivo

2020-11-19 15:38 UTC, simonhoyos commented on .vscode/settings.json
> +<<<<<<< HEAD
Puedes hacer pull de develop de una vez y solucionar los conflictos que hay con esa rama

2020-11-19 15:46 UTC, alejo9226 approved these changes
Falta quitar los punto y coma pero en cualquier commit despues se puede hacer

2020-11-19 21:31 UTC, simonhoyos approved these changes

2020-11-19 21:36 UTC, merged